# Generated by Django 2.1.7 on 2019-04-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('short_link', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('httpurl', models.URLField(max_length=264, unique=True, verbose_name='Full URL')),
            ],
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
