# Generated by Django 2.1.7 on 2019-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20190405_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
